version: '3'

services:
  db-service:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rental_fetches
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_ENV}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_ENV}
    ports:
      - 3306:3306
    container_name: db-service
    networks:
      - common-network
    volumes:
      - /data/rental-db:/var/lib/mysql
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - 61616:61616 # broker (admin:adminactivemq)(amq:amq)
      - 8161:8161   # web    http://boot2docker:8161/admin (admin:admin)
    networks:
      - common-network
  rental-fetcher-service:
    image: dariap/rental-fetcher:latest
    depends_on:
      - db-service
      - activemq
      - redis
    ports:
      - 9010:9010
    environment:
      - DB_URL=jdbc:mysql://db-service:3306/rental_fetches?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=appuser
      - DB_PASSWORD=${MYSQL_PASSWORD_ENV}
#      - BOT_TOKEN=${BOT_TOKEN_ENV}
      - SECRET_HEADER_TOKEN=${SECRET_HEADER_ENV}
      - ACTIVEMQ_PASSWORD=amq
      - ACTIVEMQ_USERNAME=amq
      - ACTIVEMQ_URL=tcp://activemq:61616
#      - REDIS_HOST=redis
    container_name: main-service
    networks:
      - common-network
    volumes:
    - /data/rental-fetcher-logs:/rental-fetcher-logs
  bot-service:
    image: dariap/rental-bot:latest
    depends_on:
      - db-service
      - activemq
      - redis
      - rental-fetcher-service
    ports:
      - 9011:9011
    environment:
      - BOT_TOKEN=${BOT_TOKEN_ENV}
      - SECRET_HEADER_TOKEN=${SECRET_HEADER_ENV}
      - ACTIVEMQ_PASSWORD=amq
      - ACTIVEMQ_USERNAME=amq
      - ACTIVEMQ_URL=tcp://activemq:61616
      - REDIS_HOST=redis
    container_name: main-service
    networks:
      - common-network
    volumes:
      - /data/bot-logs:/bot-logs
  redis:
    image: redis:rc-alpine
    ports:
      - 6379:6379
    volumes:
    - /data/bot-redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge